### ISSUE TITLE
404 on Pages for Tags 

### ISSUE THREAD

**Issue by NGenetzky** [RobertTalbert/roberttalbert.github.io#4]
It appears the your "Tags" taxonomy pages (such as [tags/#gtd](http://rtalbert.org/tags/#gtd)) are not being generated properly.

I also maintain my own static site, and I know I would appreciate if someone went through the effort to create an issue if they saw one. I actually used the same [Jekyll Theme, Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/) in the past, but I recently moved to [Academic](https://themes.gohugo.io/theme/academic/) with Hugo.

**Comment by RobertTalbert** [comment]
Thanks Nathan. Unfortunately I have never gotten tags to work correctly with this theme and nobody I have asked has ever been able to figure out why. I’ve been planning a change in platform for some time now because of the limitations of Jekyll on Github Pages and I’ll certainly be giving Hugo a look.

**Comment by NGenetzky** [comment]
Well I highly recommend Academic; I found it took minimal effort to get it up and running using [the kickstart](https://github.com/NGenetzky/hugo-academic-kickstart).

If you would prefer to get tags working; they worked on my [static site](https://ngenetzky.github.io/minimal-mistakes/tags/#minimalmistakes). I believe the file of interest is  [minimal-mistakes/_pages/tag-archive.html](https://github.com/NGenetzky/minimal-mistakes/blob/gh-pages/_pages/tag-archive.html).

Thanks for the interesting posts about GTD, and good luck with the static site.
